# Generated by Django 5.2 on 2025-04-22 12:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_photogallery_delete_photos_photo_gallery'),
    ]

    operations = [
        
    ]
