# Generated by Django 5.2 on 2025-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_thumbnail_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('wedding', 'Wedding'), ('nature', 'Nature'), ('street', 'Street'), ('family', 'Family'), ('events', 'Events'), ('document', 'Documentary')], default='portrait', max_length=20),
        ),
    ]
