# Generated by Django 5.2 on 2025-04-23 12:13

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='img/thumbnails/'),
        ),
    ]
