# Generated by Django 5.2 on 2025-04-23 12:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_review'),
    ]

    operations = [
        
    ]
